// Code generated by triggergen. DO NOT EDIT.

package triggers

import (
	"fmt"

	"github.com/juju/juju/core/database/schema"
)


// ChangeLogTriggersForGeneration generates the triggers for the
// generation table.
func ChangeLogTriggersForGeneration(columnName string, namespaceID int) func() schema.Patch {
	return func() schema.Patch {
		return schema.MakePatch(fmt.Sprintf(`
-- insert namespace for Generation
INSERT INTO change_log_namespace VALUES (%[2]d, 'generation', 'Generation changes based on %[1]s');

-- insert trigger for Generation
CREATE TRIGGER trg_log_generation_insert
AFTER INSERT ON generation FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (1, %[2]d, NEW.%[1]s, DATETIME('now', 'utc'));
END;

-- update trigger for Generation
CREATE TRIGGER trg_log_generation_update
AFTER UPDATE ON generation FOR EACH ROW
WHEN
	NEW.uuid != OLD.uuid OR
	NEW.generation_id != OLD.generation_id OR
	NEW.name != OLD.name OR
	NEW.state_id != OLD.state_id OR
	NEW.created_by != OLD.created_by OR
	NEW.created_at != OLD.created_at OR
	(NEW.completed_by != OLD.completed_by OR (NEW.completed_by IS NOT NULL AND OLD.completed_by IS NULL) OR (NEW.completed_by IS NULL AND OLD.completed_by IS NOT NULL)) OR
	(NEW.completed_at != OLD.completed_at OR (NEW.completed_at IS NOT NULL AND OLD.completed_at IS NULL) OR (NEW.completed_at IS NULL AND OLD.completed_at IS NOT NULL))
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (2, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;
-- delete trigger for Generation
CREATE TRIGGER trg_log_generation_delete
AFTER DELETE ON generation FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (4, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;`, columnName, namespaceID))
	}
}
// ChangeLogTriggersForGenerationApplication generates the triggers for the
// generation_application table.
func ChangeLogTriggersForGenerationApplication(columnName string, namespaceID int) func() schema.Patch {
	return func() schema.Patch {
		return schema.MakePatch(fmt.Sprintf(`
-- insert namespace for GenerationApplication
INSERT INTO change_log_namespace VALUES (%[2]d, 'generation_application', 'GenerationApplication changes based on %[1]s');

-- insert trigger for GenerationApplication
CREATE TRIGGER trg_log_generation_application_insert
AFTER INSERT ON generation_application FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (1, %[2]d, NEW.%[1]s, DATETIME('now', 'utc'));
END;

-- update trigger for GenerationApplication
CREATE TRIGGER trg_log_generation_application_update
AFTER UPDATE ON generation_application FOR EACH ROW
WHEN
	NEW.generation_uuid != OLD.generation_uuid OR
	NEW.application_uuid != OLD.application_uuid
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (2, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;
-- delete trigger for GenerationApplication
CREATE TRIGGER trg_log_generation_application_delete
AFTER DELETE ON generation_application FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (4, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;`, columnName, namespaceID))
	}
}

// ChangeLogTriggersForGenerationApplicationCharm generates the triggers for the
// generation_application_charm table.
func ChangeLogTriggersForGenerationApplicationCharm(columnName string, namespaceID int) func() schema.Patch {
	return func() schema.Patch {
		return schema.MakePatch(fmt.Sprintf(`
-- insert namespace for GenerationApplicationCharm
INSERT INTO change_log_namespace VALUES (%[2]d, 'generation_application_charm', 'GenerationApplicationCharm changes based on %[1]s');

-- insert trigger for GenerationApplicationCharm
CREATE TRIGGER trg_log_generation_application_charm_insert
AFTER INSERT ON generation_application_charm FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (1, %[2]d, NEW.%[1]s, DATETIME('now', 'utc'));
END;

-- update trigger for GenerationApplicationCharm
CREATE TRIGGER trg_log_generation_application_charm_update
AFTER UPDATE ON generation_application_charm FOR EACH ROW
WHEN 
	NEW.generation_uuid != OLD.generation_uuid OR
	NEW.application_uuid != OLD.application_uuid OR
	NEW.charm_uuid != OLD.charm_uuid
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (2, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;
-- delete trigger for GenerationApplicationCharm
CREATE TRIGGER trg_log_generation_application_charm_delete
AFTER DELETE ON generation_application_charm FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (4, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;`, columnName, namespaceID))
	}
}

// ChangeLogTriggersForGenerationApplicationConfig generates the triggers for the
// generation_application_config table.
func ChangeLogTriggersForGenerationApplicationConfig(columnName string, namespaceID int) func() schema.Patch {
	return func() schema.Patch {
		return schema.MakePatch(fmt.Sprintf(`
-- insert namespace for GenerationApplicationConfig
INSERT INTO change_log_namespace VALUES (%[2]d, 'generation_application_config', 'GenerationApplicationConfig changes based on %[1]s');

-- insert trigger for GenerationApplicationConfig
CREATE TRIGGER trg_log_generation_application_config_insert
AFTER INSERT ON generation_application_config FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (1, %[2]d, NEW.%[1]s, DATETIME('now', 'utc'));
END;

-- update trigger for GenerationApplicationConfig
CREATE TRIGGER trg_log_generation_application_config_update
AFTER UPDATE ON generation_application_config FOR EACH ROW
WHEN 
	NEW.generation_uuid != OLD.generation_uuid OR
	NEW.application_uuid != OLD.application_uuid OR
	NEW.key != OLD.key OR
	NEW.type_id != OLD.type_id OR
	(NEW.value != OLD.value OR (NEW.value IS NOT NULL AND OLD.value IS NULL) OR (NEW.value IS NULL AND OLD.value IS NOT NULL))
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (2, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;
-- delete trigger for GenerationApplicationConfig
CREATE TRIGGER trg_log_generation_application_config_delete
AFTER DELETE ON generation_application_config FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (4, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;`, columnName, namespaceID))
	}
}

// ChangeLogTriggersForGenerationApplicationResource generates the triggers for the
// generation_application_resource table.
func ChangeLogTriggersForGenerationApplicationResource(columnName string, namespaceID int) func() schema.Patch {
	return func() schema.Patch {
		return schema.MakePatch(fmt.Sprintf(`
-- insert namespace for GenerationApplicationResource
INSERT INTO change_log_namespace VALUES (%[2]d, 'generation_application_resource', 'GenerationApplicationResource changes based on %[1]s');

-- insert trigger for GenerationApplicationResource
CREATE TRIGGER trg_log_generation_application_resource_insert
AFTER INSERT ON generation_application_resource FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (1, %[2]d, NEW.%[1]s, DATETIME('now', 'utc'));
END;

-- update trigger for GenerationApplicationResource
CREATE TRIGGER trg_log_generation_application_resource_update
AFTER UPDATE ON generation_application_resource FOR EACH ROW
WHEN 
	NEW.generation_uuid != OLD.generation_uuid OR
	NEW.application_uuid != OLD.application_uuid OR
	NEW.charm_resource_name != OLD.charm_resource_name OR
	NEW.resource_uuid != OLD.resource_uuid
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (2, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;
-- delete trigger for GenerationApplicationResource
CREATE TRIGGER trg_log_generation_application_resource_delete
AFTER DELETE ON generation_application_resource FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (4, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;`, columnName, namespaceID))
	}
}

// ChangeLogTriggersForGenerationUnit generates the triggers for the
// generation_unit table.
func ChangeLogTriggersForGenerationUnit(columnName string, namespaceID int) func() schema.Patch {
	return func() schema.Patch {
		return schema.MakePatch(fmt.Sprintf(`
-- insert namespace for GenerationUnit
INSERT INTO change_log_namespace VALUES (%[2]d, 'generation_unit', 'GenerationUnit changes based on %[1]s');

-- insert trigger for GenerationUnit
CREATE TRIGGER trg_log_generation_unit_insert
AFTER INSERT ON generation_unit FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (1, %[2]d, NEW.%[1]s, DATETIME('now', 'utc'));
END;

-- update trigger for GenerationUnit
CREATE TRIGGER trg_log_generation_unit_update
AFTER UPDATE ON generation_unit FOR EACH ROW
WHEN 
	NEW.generation_uuid != OLD.generation_uuid OR
	NEW.unit_uuid != OLD.unit_uuid
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (2, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;
-- delete trigger for GenerationUnit
CREATE TRIGGER trg_log_generation_unit_delete
AFTER DELETE ON generation_unit FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (4, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;`, columnName, namespaceID))
	}
}
