// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/generation/service (interfaces: State)
//
// Generated by this command:
//
//	mockgen -package service -destination package_mock_test.go github.com/juju/juju/domain/generation/service State
//

// Package service is a generated GoMock package.
package service

import (
	context "context"

	gomock "github.com/canonical/gomock/gomock"
	internal "github.com/juju/juju/domain/generation/internal"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock                       *MockState
	abortExpects               []*gomock.Call3_1[context.Context, string, string, error]
	addBranchExpects           []*gomock.Call4_2[context.Context, string, string, string, uint64, error]
	commitExpects              []*gomock.Call4_2[context.Context, string, string, string, uint64, error]
	getBranchByNameExpects     []*gomock.Call2_2[context.Context, string, internal.Generation, error]
	getBranchForUnitExpects    []*gomock.Call2_2[context.Context, string, internal.Generation, error]
	getCommitExpects           []*gomock.Call2_2[context.Context, uint64, internal.Commit, error]
	getTrackedUnitNamesExpects []*gomock.Call2_2[context.Context, string, []string, error]
	hasTrackedUnitsExpects     []*gomock.Call2_2[context.Context, string, bool, error]
	listBranchesExpects        []*gomock.Call1_2[context.Context, []internal.Generation, error]
	listCommitsExpects         []*gomock.Call1_2[context.Context, []internal.Commit, error]
	trackUnitsExpects          []*gomock.Call3_1[context.Context, string, []string, error]
	untrackUnitsExpects        []*gomock.Call3_1[context.Context, string, []string, error]
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// Abort mocks base method.
func (m *MockState) Abort(ctx context.Context, generationUUID, abortedBy string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.abortExpects, m.ctrl, m, "Abort", ctx, generationUUID, abortedBy)
}

// Abort indicates an expected call of Abort.
func (mr *MockStateMockRecorder) Abort(ctx, generationUUID, abortedBy any) *MockStateAbortCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, string, error](mr.mock.ctrl.T, mr.mock, "Abort", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(generationUUID), gomock.EnsureMatcher(abortedBy))
	mr.abortExpects = append(mr.abortExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateAbortCall is the typed call wrapper for Abort.
type MockStateAbortCall = gomock.Call3_1[context.Context, string, string, error]

// AddBranch mocks base method.
func (m *MockState) AddBranch(ctx context.Context, genUUID, name, createdBy string) (uint64, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch4_2(&m.recorder.addBranchExpects, m.ctrl, m, "AddBranch", ctx, genUUID, name, createdBy)
}

// AddBranch indicates an expected call of AddBranch.
func (mr *MockStateMockRecorder) AddBranch(ctx, genUUID, name, createdBy any) *MockStateAddBranchCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall4_2[context.Context, string, string, string, uint64, error](mr.mock.ctrl.T, mr.mock, "AddBranch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(genUUID), gomock.EnsureMatcher(name), gomock.EnsureMatcher(createdBy))
	mr.addBranchExpects = append(mr.addBranchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateAddBranchCall is the typed call wrapper for AddBranch.
type MockStateAddBranchCall = gomock.Call4_2[context.Context, string, string, string, uint64, error]

// Commit mocks base method.
func (m *MockState) Commit(ctx context.Context, generationUUID, commitUUID, committedBy string) (uint64, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch4_2(&m.recorder.commitExpects, m.ctrl, m, "Commit", ctx, generationUUID, commitUUID, committedBy)
}

// Commit indicates an expected call of Commit.
func (mr *MockStateMockRecorder) Commit(ctx, generationUUID, commitUUID, committedBy any) *MockStateCommitCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall4_2[context.Context, string, string, string, uint64, error](mr.mock.ctrl.T, mr.mock, "Commit", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(generationUUID), gomock.EnsureMatcher(commitUUID), gomock.EnsureMatcher(committedBy))
	mr.commitExpects = append(mr.commitExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateCommitCall is the typed call wrapper for Commit.
type MockStateCommitCall = gomock.Call4_2[context.Context, string, string, string, uint64, error]

// GetBranchByName mocks base method.
func (m *MockState) GetBranchByName(ctx context.Context, name string) (internal.Generation, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getBranchByNameExpects, m.ctrl, m, "GetBranchByName", ctx, name)
}

// GetBranchByName indicates an expected call of GetBranchByName.
func (mr *MockStateMockRecorder) GetBranchByName(ctx, name any) *MockStateGetBranchByNameCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, internal.Generation, error](mr.mock.ctrl.T, mr.mock, "GetBranchByName", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name))
	mr.getBranchByNameExpects = append(mr.getBranchByNameExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetBranchByNameCall is the typed call wrapper for GetBranchByName.
type MockStateGetBranchByNameCall = gomock.Call2_2[context.Context, string, internal.Generation, error]

// GetBranchForUnit mocks base method.
func (m *MockState) GetBranchForUnit(ctx context.Context, unitUUID string) (internal.Generation, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getBranchForUnitExpects, m.ctrl, m, "GetBranchForUnit", ctx, unitUUID)
}

// GetBranchForUnit indicates an expected call of GetBranchForUnit.
func (mr *MockStateMockRecorder) GetBranchForUnit(ctx, unitUUID any) *MockStateGetBranchForUnitCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, internal.Generation, error](mr.mock.ctrl.T, mr.mock, "GetBranchForUnit", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(unitUUID))
	mr.getBranchForUnitExpects = append(mr.getBranchForUnitExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetBranchForUnitCall is the typed call wrapper for GetBranchForUnit.
type MockStateGetBranchForUnitCall = gomock.Call2_2[context.Context, string, internal.Generation, error]

// GetCommit mocks base method.
func (m *MockState) GetCommit(ctx context.Context, generationID uint64) (internal.Commit, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getCommitExpects, m.ctrl, m, "GetCommit", ctx, generationID)
}

// GetCommit indicates an expected call of GetCommit.
func (mr *MockStateMockRecorder) GetCommit(ctx, generationID any) *MockStateGetCommitCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, uint64, internal.Commit, error](mr.mock.ctrl.T, mr.mock, "GetCommit", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(generationID))
	mr.getCommitExpects = append(mr.getCommitExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetCommitCall is the typed call wrapper for GetCommit.
type MockStateGetCommitCall = gomock.Call2_2[context.Context, uint64, internal.Commit, error]

// GetTrackedUnitNames mocks base method.
func (m *MockState) GetTrackedUnitNames(ctx context.Context, generationUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getTrackedUnitNamesExpects, m.ctrl, m, "GetTrackedUnitNames", ctx, generationUUID)
}

// GetTrackedUnitNames indicates an expected call of GetTrackedUnitNames.
func (mr *MockStateMockRecorder) GetTrackedUnitNames(ctx, generationUUID any) *MockStateGetTrackedUnitNamesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, []string, error](mr.mock.ctrl.T, mr.mock, "GetTrackedUnitNames", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(generationUUID))
	mr.getTrackedUnitNamesExpects = append(mr.getTrackedUnitNamesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetTrackedUnitNamesCall is the typed call wrapper for GetTrackedUnitNames.
type MockStateGetTrackedUnitNamesCall = gomock.Call2_2[context.Context, string, []string, error]

// HasTrackedUnits mocks base method.
func (m *MockState) HasTrackedUnits(ctx context.Context, generationUUID string) (bool, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.hasTrackedUnitsExpects, m.ctrl, m, "HasTrackedUnits", ctx, generationUUID)
}

// HasTrackedUnits indicates an expected call of HasTrackedUnits.
func (mr *MockStateMockRecorder) HasTrackedUnits(ctx, generationUUID any) *MockStateHasTrackedUnitsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, bool, error](mr.mock.ctrl.T, mr.mock, "HasTrackedUnits", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(generationUUID))
	mr.hasTrackedUnitsExpects = append(mr.hasTrackedUnitsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateHasTrackedUnitsCall is the typed call wrapper for HasTrackedUnits.
type MockStateHasTrackedUnitsCall = gomock.Call2_2[context.Context, string, bool, error]

// ListBranches mocks base method.
func (m *MockState) ListBranches(ctx context.Context) ([]internal.Generation, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.listBranchesExpects, m.ctrl, m, "ListBranches", ctx)
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockStateMockRecorder) ListBranches(ctx any) *MockStateListBranchesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, []internal.Generation, error](mr.mock.ctrl.T, mr.mock, "ListBranches", gomock.EnsureMatcher(ctx))
	mr.listBranchesExpects = append(mr.listBranchesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateListBranchesCall is the typed call wrapper for ListBranches.
type MockStateListBranchesCall = gomock.Call1_2[context.Context, []internal.Generation, error]

// ListCommits mocks base method.
func (m *MockState) ListCommits(ctx context.Context) ([]internal.Commit, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.listCommitsExpects, m.ctrl, m, "ListCommits", ctx)
}

// ListCommits indicates an expected call of ListCommits.
func (mr *MockStateMockRecorder) ListCommits(ctx any) *MockStateListCommitsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, []internal.Commit, error](mr.mock.ctrl.T, mr.mock, "ListCommits", gomock.EnsureMatcher(ctx))
	mr.listCommitsExpects = append(mr.listCommitsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateListCommitsCall is the typed call wrapper for ListCommits.
type MockStateListCommitsCall = gomock.Call1_2[context.Context, []internal.Commit, error]

// TrackUnits mocks base method.
func (m *MockState) TrackUnits(ctx context.Context, generationUUID string, unitUUIDs []string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.trackUnitsExpects, m.ctrl, m, "TrackUnits", ctx, generationUUID, unitUUIDs)
}

// TrackUnits indicates an expected call of TrackUnits.
func (mr *MockStateMockRecorder) TrackUnits(ctx, generationUUID, unitUUIDs any) *MockStateTrackUnitsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, []string, error](mr.mock.ctrl.T, mr.mock, "TrackUnits", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(generationUUID), gomock.EnsureMatcher(unitUUIDs))
	mr.trackUnitsExpects = append(mr.trackUnitsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateTrackUnitsCall is the typed call wrapper for TrackUnits.
type MockStateTrackUnitsCall = gomock.Call3_1[context.Context, string, []string, error]

// UntrackUnits mocks base method.
func (m *MockState) UntrackUnits(ctx context.Context, generationUUID string, unitUUIDs []string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.untrackUnitsExpects, m.ctrl, m, "UntrackUnits", ctx, generationUUID, unitUUIDs)
}

// UntrackUnits indicates an expected call of UntrackUnits.
func (mr *MockStateMockRecorder) UntrackUnits(ctx, generationUUID, unitUUIDs any) *MockStateUntrackUnitsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, []string, error](mr.mock.ctrl.T, mr.mock, "UntrackUnits", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(generationUUID), gomock.EnsureMatcher(unitUUIDs))
	mr.untrackUnitsExpects = append(mr.untrackUnitsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateUntrackUnitsCall is the typed call wrapper for UntrackUnits.
type MockStateUntrackUnitsCall = gomock.Call3_1[context.Context, string, []string, error]
