// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/blockdevice/service (interfaces: State,WatcherFactory)
//
// Generated by this command:
//
//	mockgen -typed -package service -destination state_mock_test.go github.com/juju/juju/domain/blockdevice/service State,WatcherFactory
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	blockdevice "github.com/juju/juju/core/blockdevice"
	watcher "github.com/juju/juju/core/watcher"
	eventsource "github.com/juju/juju/core/watcher/eventsource"
	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// BlockDeviceMachineUUID mocks base method.
func (m *MockState) BlockDeviceMachineUUID(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockDeviceMachineUUID", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockDeviceMachineUUID indicates an expected call of BlockDeviceMachineUUID.
func (mr *MockStateMockRecorder) BlockDeviceMachineUUID(arg0, arg1 any) *MockStateBlockDeviceMachineUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockDeviceMachineUUID", reflect.TypeOf((*MockState)(nil).BlockDeviceMachineUUID), arg0, arg1)
	return &MockStateBlockDeviceMachineUUIDCall{Call: call}
}

// MockStateBlockDeviceMachineUUIDCall wrap *gomock.Call
type MockStateBlockDeviceMachineUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateBlockDeviceMachineUUIDCall) Return(arg0 string, arg1 error) *MockStateBlockDeviceMachineUUIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateBlockDeviceMachineUUIDCall) Do(f func(context.Context, string) (string, error)) *MockStateBlockDeviceMachineUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateBlockDeviceMachineUUIDCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockStateBlockDeviceMachineUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BlockDevices mocks base method.
func (m *MockState) BlockDevices(arg0 context.Context, arg1 string) ([]blockdevice.BlockDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockDevices", arg0, arg1)
	ret0, _ := ret[0].([]blockdevice.BlockDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockDevices indicates an expected call of BlockDevices.
func (mr *MockStateMockRecorder) BlockDevices(arg0, arg1 any) *MockStateBlockDevicesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockDevices", reflect.TypeOf((*MockState)(nil).BlockDevices), arg0, arg1)
	return &MockStateBlockDevicesCall{Call: call}
}

// MockStateBlockDevicesCall wrap *gomock.Call
type MockStateBlockDevicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateBlockDevicesCall) Return(arg0 []blockdevice.BlockDevice, arg1 error) *MockStateBlockDevicesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateBlockDevicesCall) Do(f func(context.Context, string) ([]blockdevice.BlockDevice, error)) *MockStateBlockDevicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateBlockDevicesCall) DoAndReturn(f func(context.Context, string) ([]blockdevice.BlockDevice, error)) *MockStateBlockDevicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MachineBlockDevices mocks base method.
func (m *MockState) MachineBlockDevices(arg0 context.Context) ([]blockdevice.MachineBlockDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MachineBlockDevices", arg0)
	ret0, _ := ret[0].([]blockdevice.MachineBlockDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MachineBlockDevices indicates an expected call of MachineBlockDevices.
func (mr *MockStateMockRecorder) MachineBlockDevices(arg0 any) *MockStateMachineBlockDevicesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MachineBlockDevices", reflect.TypeOf((*MockState)(nil).MachineBlockDevices), arg0)
	return &MockStateMachineBlockDevicesCall{Call: call}
}

// MockStateMachineBlockDevicesCall wrap *gomock.Call
type MockStateMachineBlockDevicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateMachineBlockDevicesCall) Return(arg0 []blockdevice.MachineBlockDevice, arg1 error) *MockStateMachineBlockDevicesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateMachineBlockDevicesCall) Do(f func(context.Context) ([]blockdevice.MachineBlockDevice, error)) *MockStateMachineBlockDevicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateMachineBlockDevicesCall) DoAndReturn(f func(context.Context) ([]blockdevice.MachineBlockDevice, error)) *MockStateMachineBlockDevicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetMachineBlockDevices mocks base method.
func (m *MockState) SetMachineBlockDevices(arg0 context.Context, arg1 string, arg2 ...blockdevice.BlockDevice) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetMachineBlockDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMachineBlockDevices indicates an expected call of SetMachineBlockDevices.
func (mr *MockStateMockRecorder) SetMachineBlockDevices(arg0, arg1 any, arg2 ...any) *MockStateSetMachineBlockDevicesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMachineBlockDevices", reflect.TypeOf((*MockState)(nil).SetMachineBlockDevices), varargs...)
	return &MockStateSetMachineBlockDevicesCall{Call: call}
}

// MockStateSetMachineBlockDevicesCall wrap *gomock.Call
type MockStateSetMachineBlockDevicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateSetMachineBlockDevicesCall) Return(arg0 error) *MockStateSetMachineBlockDevicesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateSetMachineBlockDevicesCall) Do(f func(context.Context, string, ...blockdevice.BlockDevice) error) *MockStateSetMachineBlockDevicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateSetMachineBlockDevicesCall) DoAndReturn(f func(context.Context, string, ...blockdevice.BlockDevice) error) *MockStateSetMachineBlockDevicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWatcherFactory is a mock of WatcherFactory interface.
type MockWatcherFactory struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherFactoryMockRecorder
}

// MockWatcherFactoryMockRecorder is the mock recorder for MockWatcherFactory.
type MockWatcherFactoryMockRecorder struct {
	mock *MockWatcherFactory
}

// NewMockWatcherFactory creates a new mock instance.
func NewMockWatcherFactory(ctrl *gomock.Controller) *MockWatcherFactory {
	mock := &MockWatcherFactory{ctrl: ctrl}
	mock.recorder = &MockWatcherFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcherFactory) EXPECT() *MockWatcherFactoryMockRecorder {
	return m.recorder
}

// NewMultiWatcher mocks base method.
func (m *MockWatcherFactory) NewMultiWatcher(arg0 ...eventsource.FilterOption) (watcher.Watcher[struct{}], error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMultiWatcher", varargs...)
	ret0, _ := ret[0].(watcher.Watcher[struct{}])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMultiWatcher indicates an expected call of NewMultiWatcher.
func (mr *MockWatcherFactoryMockRecorder) NewMultiWatcher(arg0 ...any) *MockWatcherFactoryNewMultiWatcherCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMultiWatcher", reflect.TypeOf((*MockWatcherFactory)(nil).NewMultiWatcher), arg0...)
	return &MockWatcherFactoryNewMultiWatcherCall{Call: call}
}

// MockWatcherFactoryNewMultiWatcherCall wrap *gomock.Call
type MockWatcherFactoryNewMultiWatcherCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWatcherFactoryNewMultiWatcherCall) Return(arg0 watcher.Watcher[struct{}], arg1 error) *MockWatcherFactoryNewMultiWatcherCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWatcherFactoryNewMultiWatcherCall) Do(f func(...eventsource.FilterOption) (watcher.Watcher[struct{}], error)) *MockWatcherFactoryNewMultiWatcherCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWatcherFactoryNewMultiWatcherCall) DoAndReturn(f func(...eventsource.FilterOption) (watcher.Watcher[struct{}], error)) *MockWatcherFactoryNewMultiWatcherCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
