// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/apiserver/facades/client/modelgeneration (interfaces: GenerationService,ApplicationService)
//
// Generated by this command:
//
//	mockgen -package modelgeneration -destination service_mock_test.go github.com/juju/juju/apiserver/facades/client/modelgeneration GenerationService,ApplicationService
//

// Package modelgeneration is a generated GoMock package.
package modelgeneration

import (
	context "context"

	gomock "github.com/canonical/gomock/gomock"
	unit "github.com/juju/juju/core/unit"
	generation "github.com/juju/juju/domain/generation"
)

// MockGenerationService is a mock of GenerationService interface.
type MockGenerationService struct {
	ctrl     *gomock.Controller
	recorder *MockGenerationServiceMockRecorder
	isgomock struct{}
}

// MockGenerationServiceMockRecorder is the mock recorder for MockGenerationService.
type MockGenerationServiceMockRecorder struct {
	mock                   *MockGenerationService
	abortBranchExpects     []*gomock.Call3_1[context.Context, string, string, error]
	addBranchExpects       []*gomock.Call3_2[context.Context, string, string, uint64, error]
	commitBranchExpects    []*gomock.Call3_2[context.Context, string, string, uint64, error]
	getBranchByNameExpects []*gomock.Call2_2[context.Context, string, generation.Generation, error]
	getCommitExpects       []*gomock.Call2_2[context.Context, uint64, generation.Commit, error]
	getTrackedUnitsExpects []*gomock.Call2_2[context.Context, string, []unit.Name, error]
	listBranchesExpects    []*gomock.Call1_2[context.Context, []generation.Generation, error]
	listCommitsExpects     []*gomock.Call1_2[context.Context, []generation.Commit, error]
	trackBranchExpects     []*gomock.Call3_1[context.Context, string, []unit.UUID, error]
	untrackBranchExpects   []*gomock.Call3_1[context.Context, string, []unit.UUID, error]
}

// NewMockGenerationService creates a new mock instance.
func NewMockGenerationService(ctrl *gomock.Controller) *MockGenerationService {
	mock := &MockGenerationService{ctrl: ctrl}
	mock.recorder = &MockGenerationServiceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerationService) EXPECT() *MockGenerationServiceMockRecorder {
	return m.recorder
}

// AbortBranch mocks base method.
func (m *MockGenerationService) AbortBranch(ctx context.Context, branchName, abortedBy string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.abortBranchExpects, m.ctrl, m, "AbortBranch", ctx, branchName, abortedBy)
}

// AbortBranch indicates an expected call of AbortBranch.
func (mr *MockGenerationServiceMockRecorder) AbortBranch(ctx, branchName, abortedBy any) *MockGenerationServiceAbortBranchCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, string, error](mr.mock.ctrl.T, mr.mock, "AbortBranch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(branchName), gomock.EnsureMatcher(abortedBy))
	mr.abortBranchExpects = append(mr.abortBranchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceAbortBranchCall is the typed call wrapper for AbortBranch.
type MockGenerationServiceAbortBranchCall = gomock.Call3_1[context.Context, string, string, error]

// AddBranch mocks base method.
func (m *MockGenerationService) AddBranch(ctx context.Context, name, createdBy string) (uint64, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.addBranchExpects, m.ctrl, m, "AddBranch", ctx, name, createdBy)
}

// AddBranch indicates an expected call of AddBranch.
func (mr *MockGenerationServiceMockRecorder) AddBranch(ctx, name, createdBy any) *MockGenerationServiceAddBranchCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, string, string, uint64, error](mr.mock.ctrl.T, mr.mock, "AddBranch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name), gomock.EnsureMatcher(createdBy))
	mr.addBranchExpects = append(mr.addBranchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceAddBranchCall is the typed call wrapper for AddBranch.
type MockGenerationServiceAddBranchCall = gomock.Call3_2[context.Context, string, string, uint64, error]

// CommitBranch mocks base method.
func (m *MockGenerationService) CommitBranch(ctx context.Context, branchName, committedBy string) (uint64, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.commitBranchExpects, m.ctrl, m, "CommitBranch", ctx, branchName, committedBy)
}

// CommitBranch indicates an expected call of CommitBranch.
func (mr *MockGenerationServiceMockRecorder) CommitBranch(ctx, branchName, committedBy any) *MockGenerationServiceCommitBranchCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, string, string, uint64, error](mr.mock.ctrl.T, mr.mock, "CommitBranch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(branchName), gomock.EnsureMatcher(committedBy))
	mr.commitBranchExpects = append(mr.commitBranchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceCommitBranchCall is the typed call wrapper for CommitBranch.
type MockGenerationServiceCommitBranchCall = gomock.Call3_2[context.Context, string, string, uint64, error]

// GetBranchByName mocks base method.
func (m *MockGenerationService) GetBranchByName(ctx context.Context, name string) (generation.Generation, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getBranchByNameExpects, m.ctrl, m, "GetBranchByName", ctx, name)
}

// GetBranchByName indicates an expected call of GetBranchByName.
func (mr *MockGenerationServiceMockRecorder) GetBranchByName(ctx, name any) *MockGenerationServiceGetBranchByNameCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, generation.Generation, error](mr.mock.ctrl.T, mr.mock, "GetBranchByName", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name))
	mr.getBranchByNameExpects = append(mr.getBranchByNameExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceGetBranchByNameCall is the typed call wrapper for GetBranchByName.
type MockGenerationServiceGetBranchByNameCall = gomock.Call2_2[context.Context, string, generation.Generation, error]

// GetCommit mocks base method.
func (m *MockGenerationService) GetCommit(ctx context.Context, generationID uint64) (generation.Commit, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getCommitExpects, m.ctrl, m, "GetCommit", ctx, generationID)
}

// GetCommit indicates an expected call of GetCommit.
func (mr *MockGenerationServiceMockRecorder) GetCommit(ctx, generationID any) *MockGenerationServiceGetCommitCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, uint64, generation.Commit, error](mr.mock.ctrl.T, mr.mock, "GetCommit", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(generationID))
	mr.getCommitExpects = append(mr.getCommitExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceGetCommitCall is the typed call wrapper for GetCommit.
type MockGenerationServiceGetCommitCall = gomock.Call2_2[context.Context, uint64, generation.Commit, error]

// GetTrackedUnits mocks base method.
func (m *MockGenerationService) GetTrackedUnits(ctx context.Context, branchName string) ([]unit.Name, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getTrackedUnitsExpects, m.ctrl, m, "GetTrackedUnits", ctx, branchName)
}

// GetTrackedUnits indicates an expected call of GetTrackedUnits.
func (mr *MockGenerationServiceMockRecorder) GetTrackedUnits(ctx, branchName any) *MockGenerationServiceGetTrackedUnitsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, []unit.Name, error](mr.mock.ctrl.T, mr.mock, "GetTrackedUnits", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(branchName))
	mr.getTrackedUnitsExpects = append(mr.getTrackedUnitsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceGetTrackedUnitsCall is the typed call wrapper for GetTrackedUnits.
type MockGenerationServiceGetTrackedUnitsCall = gomock.Call2_2[context.Context, string, []unit.Name, error]

// ListBranches mocks base method.
func (m *MockGenerationService) ListBranches(ctx context.Context) ([]generation.Generation, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.listBranchesExpects, m.ctrl, m, "ListBranches", ctx)
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockGenerationServiceMockRecorder) ListBranches(ctx any) *MockGenerationServiceListBranchesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, []generation.Generation, error](mr.mock.ctrl.T, mr.mock, "ListBranches", gomock.EnsureMatcher(ctx))
	mr.listBranchesExpects = append(mr.listBranchesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceListBranchesCall is the typed call wrapper for ListBranches.
type MockGenerationServiceListBranchesCall = gomock.Call1_2[context.Context, []generation.Generation, error]

// ListCommits mocks base method.
func (m *MockGenerationService) ListCommits(ctx context.Context) ([]generation.Commit, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.listCommitsExpects, m.ctrl, m, "ListCommits", ctx)
}

// ListCommits indicates an expected call of ListCommits.
func (mr *MockGenerationServiceMockRecorder) ListCommits(ctx any) *MockGenerationServiceListCommitsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, []generation.Commit, error](mr.mock.ctrl.T, mr.mock, "ListCommits", gomock.EnsureMatcher(ctx))
	mr.listCommitsExpects = append(mr.listCommitsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceListCommitsCall is the typed call wrapper for ListCommits.
type MockGenerationServiceListCommitsCall = gomock.Call1_2[context.Context, []generation.Commit, error]

// TrackBranch mocks base method.
func (m *MockGenerationService) TrackBranch(ctx context.Context, branchName string, unitUUIDs []unit.UUID) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.trackBranchExpects, m.ctrl, m, "TrackBranch", ctx, branchName, unitUUIDs)
}

// TrackBranch indicates an expected call of TrackBranch.
func (mr *MockGenerationServiceMockRecorder) TrackBranch(ctx, branchName, unitUUIDs any) *MockGenerationServiceTrackBranchCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, []unit.UUID, error](mr.mock.ctrl.T, mr.mock, "TrackBranch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(branchName), gomock.EnsureMatcher(unitUUIDs))
	mr.trackBranchExpects = append(mr.trackBranchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceTrackBranchCall is the typed call wrapper for TrackBranch.
type MockGenerationServiceTrackBranchCall = gomock.Call3_1[context.Context, string, []unit.UUID, error]

// UntrackBranch mocks base method.
func (m *MockGenerationService) UntrackBranch(ctx context.Context, branchName string, unitUUIDs []unit.UUID) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.untrackBranchExpects, m.ctrl, m, "UntrackBranch", ctx, branchName, unitUUIDs)
}

// UntrackBranch indicates an expected call of UntrackBranch.
func (mr *MockGenerationServiceMockRecorder) UntrackBranch(ctx, branchName, unitUUIDs any) *MockGenerationServiceUntrackBranchCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, []unit.UUID, error](mr.mock.ctrl.T, mr.mock, "UntrackBranch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(branchName), gomock.EnsureMatcher(unitUUIDs))
	mr.untrackBranchExpects = append(mr.untrackBranchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerationServiceUntrackBranchCall is the typed call wrapper for UntrackBranch.
type MockGenerationServiceUntrackBranchCall = gomock.Call3_1[context.Context, string, []unit.UUID, error]

// MockApplicationService is a mock of ApplicationService interface.
type MockApplicationService struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationServiceMockRecorder
	isgomock struct{}
}

// MockApplicationServiceMockRecorder is the mock recorder for MockApplicationService.
type MockApplicationServiceMockRecorder struct {
	mock                              *MockApplicationService
	getUnitNamesForApplicationExpects []*gomock.Call2_2[context.Context, string, []unit.Name, error]
	getUnitUUIDExpects                []*gomock.Call2_2[context.Context, unit.Name, unit.UUID, error]
}

// NewMockApplicationService creates a new mock instance.
func NewMockApplicationService(ctrl *gomock.Controller) *MockApplicationService {
	mock := &MockApplicationService{ctrl: ctrl}
	mock.recorder = &MockApplicationServiceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationService) EXPECT() *MockApplicationServiceMockRecorder {
	return m.recorder
}

// GetUnitNamesForApplication mocks base method.
func (m *MockApplicationService) GetUnitNamesForApplication(ctx context.Context, appName string) ([]unit.Name, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getUnitNamesForApplicationExpects, m.ctrl, m, "GetUnitNamesForApplication", ctx, appName)
}

// GetUnitNamesForApplication indicates an expected call of GetUnitNamesForApplication.
func (mr *MockApplicationServiceMockRecorder) GetUnitNamesForApplication(ctx, appName any) *MockApplicationServiceGetUnitNamesForApplicationCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, []unit.Name, error](mr.mock.ctrl.T, mr.mock, "GetUnitNamesForApplication", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(appName))
	mr.getUnitNamesForApplicationExpects = append(mr.getUnitNamesForApplicationExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockApplicationServiceGetUnitNamesForApplicationCall is the typed call wrapper for GetUnitNamesForApplication.
type MockApplicationServiceGetUnitNamesForApplicationCall = gomock.Call2_2[context.Context, string, []unit.Name, error]

// GetUnitUUID mocks base method.
func (m *MockApplicationService) GetUnitUUID(ctx context.Context, unitName unit.Name) (unit.UUID, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getUnitUUIDExpects, m.ctrl, m, "GetUnitUUID", ctx, unitName)
}

// GetUnitUUID indicates an expected call of GetUnitUUID.
func (mr *MockApplicationServiceMockRecorder) GetUnitUUID(ctx, unitName any) *MockApplicationServiceGetUnitUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, unit.Name, unit.UUID, error](mr.mock.ctrl.T, mr.mock, "GetUnitUUID", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(unitName))
	mr.getUnitUUIDExpects = append(mr.getUnitUUIDExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockApplicationServiceGetUnitUUIDCall is the typed call wrapper for GetUnitUUID.
type MockApplicationServiceGetUnitUUIDCall = gomock.Call2_2[context.Context, unit.Name, unit.UUID, error]
