// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/internal/worker/scriptlets (interfaces: ScriptletService)
//
// Generated by this command:
//
//	mockgen -typed -package scriptlets -destination service_mock_test.go github.com/juju/juju/internal/worker/scriptlets ScriptletService
//

// Package scriptlets is a generated GoMock package.
package scriptlets

import (
	context "context"
	reflect "reflect"

	watcher "github.com/juju/juju/core/watcher"
	gomock "go.uber.org/mock/gomock"
)

// MockScriptletService is a mock of ScriptletService interface.
type MockScriptletService struct {
	ctrl     *gomock.Controller
	recorder *MockScriptletServiceMockRecorder
}

// MockScriptletServiceMockRecorder is the mock recorder for MockScriptletService.
type MockScriptletServiceMockRecorder struct {
	mock *MockScriptletService
}

// NewMockScriptletService creates a new mock instance.
func NewMockScriptletService(ctrl *gomock.Controller) *MockScriptletService {
	mock := &MockScriptletService{ctrl: ctrl}
	mock.recorder = &MockScriptletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptletService) EXPECT() *MockScriptletServiceMockRecorder {
	return m.recorder
}

// GetScript mocks base method.
func (m *MockScriptletService) GetScript(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScript", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScript indicates an expected call of GetScript.
func (mr *MockScriptletServiceMockRecorder) GetScript(arg0, arg1 any) *MockScriptletServiceGetScriptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScript", reflect.TypeOf((*MockScriptletService)(nil).GetScript), arg0, arg1)
	return &MockScriptletServiceGetScriptCall{Call: call}
}

// MockScriptletServiceGetScriptCall wrap *gomock.Call
type MockScriptletServiceGetScriptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScriptletServiceGetScriptCall) Return(arg0 string, arg1 error) *MockScriptletServiceGetScriptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScriptletServiceGetScriptCall) Do(f func(context.Context, string) (string, error)) *MockScriptletServiceGetScriptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScriptletServiceGetScriptCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockScriptletServiceGetScriptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WatchScriptlets mocks base method.
func (m *MockScriptletService) WatchScriptlets(arg0 context.Context) (watcher.Watcher[[]string], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchScriptlets", arg0)
	ret0, _ := ret[0].(watcher.Watcher[[]string])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchScriptlets indicates an expected call of WatchScriptlets.
func (mr *MockScriptletServiceMockRecorder) WatchScriptlets(arg0 any) *MockScriptletServiceWatchScriptletsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchScriptlets", reflect.TypeOf((*MockScriptletService)(nil).WatchScriptlets), arg0)
	return &MockScriptletServiceWatchScriptletsCall{Call: call}
}

// MockScriptletServiceWatchScriptletsCall wrap *gomock.Call
type MockScriptletServiceWatchScriptletsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScriptletServiceWatchScriptletsCall) Return(arg0 watcher.Watcher[[]string], arg1 error) *MockScriptletServiceWatchScriptletsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScriptletServiceWatchScriptletsCall) Do(f func(context.Context) (watcher.Watcher[[]string], error)) *MockScriptletServiceWatchScriptletsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScriptletServiceWatchScriptletsCall) DoAndReturn(f func(context.Context) (watcher.Watcher[[]string], error)) *MockScriptletServiceWatchScriptletsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
