name: "Update homebrew tap"
on:
  release:
    types: [published]
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-brew-tap:
    permissions:
      contents: none
    if: github.repository_owner == 'juju'
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@baf2b60c51fc1f8453c884b0c61052668a71bd1d # master
        with:
          token: "${{ secrets.TOKEN }}"
          formula: juju
          livecheck: true
